name: Waypoint
version: '${project.version}'
main: me.alvaro.waypoint.Waypoint
api-version: 1.19
authors: [ Alvaro ]
description: Criar e listar coordenadas de forma simples
commands:
  waypointAdd:
    description: Adicionar uma nova coordenada a lista de coordenadas
    aliases:
      - wadd
    usage: "Uso: /<command> nomeCoordenada X Y Z"
  waypointList:
    description: Listar todas coordendas salvas
    aliases:
      - wlist
    usage: "Uso: /<command>"
  waypointBook:
    description: Receber um livro com todas coordenadas salvas
    aliases:
      - wbook
    usage: "Uso: /<command>"
  waypointRemove:
    description: Remover uma coordenada salva pelo seu ID
    aliases:
      - wremove
    usage: "Uso: /<command> ID"
  waypointAddCurrent:
    description: Adicionar a coordenada atual a lista de coordenadas
    aliases:
      - waddcur
    usage: "Uso: /<command> nomeCoordenada"