name: Waypoint
version: '${project.version}'
main: me.alvaro.waypoint.Waypoint
api-version: 1.19
authors: [ Alvaro ]
description: Criar e listar coordenadas de forma simples
commands:
  waypointAdd:
    description: Adicionar uma nova coordenada a lista de coordenadas
    aliases:
      - wadd
    usage: /<command> [nomeCoordenada] [X] [Y] [Z]
  waypointList:
    description: Listar todas coordendas salvas
    aliases:
      - wlist
    usage: /<command>